spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Jonathan931/microservices-java/
          search-paths: git-localconfig-server

server:
  port: 8888

